/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author Aline
 */
public class TelaElevador extends javax.swing.JFrame {

    /**
     * Creates new form TelaElevador
     */
    public TelaElevador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CorParede = new javax.swing.JPanel();
        btn3Andar = new javax.swing.JButton();
        btn2Andar = new javax.swing.JButton();
        btn1Andar = new javax.swing.JButton();
        btnTerreo = new javax.swing.JButton();
        PainelAndares = new javax.swing.JLabel();
        VisorAndar = new javax.swing.JLabel();
        Elevador = new javax.swing.JLabel();
        DecoracaoParede = new javax.swing.JLabel();
        DecoracaoChao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CorParede.setBackground(new java.awt.Color(153, 204, 255));
        CorParede.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3Andar.setText("3");
        CorParede.add(btn3Andar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 80, -1));

        btn2Andar.setText("2");
        CorParede.add(btn2Andar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, 80, -1));

        btn1Andar.setText("1");
        btn1Andar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1AndarActionPerformed(evt);
            }
        });
        CorParede.add(btn1Andar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, 80, -1));

        btnTerreo.setText("Terreo");
        CorParede.add(btnTerreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 390, 80, -1));

        PainelAndares.setOpaque(true);
        CorParede.add(PainelAndares, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, 80, 130));

        VisorAndar.setOpaque(true);
        CorParede.add(VisorAndar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 133, 48));

        Elevador.setOpaque(true);
        CorParede.add(Elevador, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 656, 703));

        DecoracaoParede.setOpaque(true);
        CorParede.add(DecoracaoParede, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 290, 336));

        DecoracaoChao.setOpaque(true);
        CorParede.add(DecoracaoChao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 460, 250, 340));

        getContentPane().add(CorParede, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1AndarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1AndarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1AndarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaElevador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CorParede;
    private javax.swing.JLabel DecoracaoChao;
    private javax.swing.JLabel DecoracaoParede;
    private javax.swing.JLabel Elevador;
    private javax.swing.JLabel PainelAndares;
    private javax.swing.JLabel VisorAndar;
    private javax.swing.JButton btn1Andar;
    private javax.swing.JButton btn2Andar;
    private javax.swing.JButton btn3Andar;
    private javax.swing.JButton btnTerreo;
    // End of variables declaration//GEN-END:variables
}
