/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Color;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author Aline
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaMenu() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVendingMachine = new javax.swing.JButton();
        btnElevador = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Backgroud = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setMinimumSize(new java.awt.Dimension(583, 373));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVendingMachine.setBackground(new java.awt.Color(153, 255, 255));
        btnVendingMachine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVendingMachine.setText("VENDING MACHINE");
        btnVendingMachine.setBorder(null);
        btnVendingMachine.setContentAreaFilled(false);
        btnVendingMachine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendingMachine.setOpaque(true);
        btnVendingMachine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendingMachineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendingMachineMouseExited(evt);
            }
        });
        btnVendingMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendingMachineActionPerformed(evt);
            }
        });
        getContentPane().add(btnVendingMachine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 280, 80));

        btnElevador.setBackground(new java.awt.Color(153, 255, 255));
        btnElevador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnElevador.setText("ELEVADOR");
        btnElevador.setBorder(null);
        btnElevador.setContentAreaFilled(false);
        btnElevador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElevador.setOpaque(true);
        btnElevador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnElevadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnElevadorMouseExited(evt);
            }
        });
        btnElevador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElevadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnElevador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 280, 80));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("CASES");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, 50));

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensVendingMachine/BackgroundMenu.jpg"))); // NOI18N
        getContentPane().add(Backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void btnVendingMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendingMachineActionPerformed
        TelaVendingMachine vendingMachine = new TelaVendingMachine();
        vendingMachine.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVendingMachineActionPerformed

    private void btnVendingMachineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendingMachineMouseEntered
        btnVendingMachine.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_btnVendingMachineMouseEntered

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnVendingMachineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendingMachineMouseExited
        btnVendingMachine.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_btnVendingMachineMouseExited

    private void btnElevadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElevadorMouseEntered
        btnElevador.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_btnElevadorMouseEntered

    private void btnElevadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElevadorMouseExited
        btnElevador.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_btnElevadorMouseExited

    private void btnElevadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElevadorActionPerformed
        TelaElevador elevador = new TelaElevador();
        elevador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnElevadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnElevador;
    private javax.swing.JButton btnVendingMachine;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
